
select sys_context( 'userenv', 'current_schema' ) from dual;


desc CE_A2_BANK_ACCOUNT;


CREATE TABLE "TH_IM1_CREDIT_CARD"
(
   TH_CRC_RECID NUMBER,
   TH_CRC_OWNER VARCHAR2(300),
   TH_CRC_NUMBER VARCHAR2(25),
   TH_CRC_EXP_MONTH VARCHAR2(10),
   TH_CRC_EXP_YEAR VARCHAR2(5),
   CONSTRAINT "TH_IM1_CREDIT_CARD_PK" PRIMARY KEY("TH_CRC_RECID")
);
CREATE SEQUENCE SEQ_TH_IM1_CREDIT_CARD_RECID MINVALUE 0 START WITH 0 INCREMENT BY 1 NOCACHE NOCYCLE;

INSERT INTO TH_IM1_CREDIT_CARD VALUES(SEQ_TH_IM1_CREDIT_CARD_RECID.NEXTVAL, 'Garry Kasparov', '1234 2345 3456 4567', '23/11', '2018');
INSERT INTO TH_IM1_CREDIT_CARD VALUES(SEQ_TH_IM1_CREDIT_CARD_RECID.NEXTVAL, 'Anatoly Karpov', '2334 4545 8712 3454', '14/07', '2019');

CREATE TABLE "TH_IM1_BANK_ACCOUNT"
(
   TH_BACC_RECID NUMBER,
   TH_BACC_OWNER VARCHAR2(300),
   TH_BACC_ACCOUNT VARCHAR2(100),
   TH_BACC_BANKNAME VARCHAR2(100),
   TH_BACC_SWIFT VARCHAR2(100),
   CONSTRAINT "TH_IM1_BANK_ACCOUNT_PK" PRIMARY KEY("TH_BACC_RECID")
);
CREATE SEQUENCE SEQ_TH_IM1_BANK_ACCOUNT_RECID MINVALUE 0 START WITH 0 INCREMENT BY 1 NOCACHE NOCYCLE;

INSERT INTO TH_IM1_BANK_ACCOUNT VALUES(SEQ_TH_IM1_BANK_ACCOUNT_RECID.NEXTVAL, 'Mikhail Botvinnik', 'FW45F32SQ12', 'Private Bank', '2380');
INSERT INTO TH_IM1_BANK_ACCOUNT VALUES(SEQ_TH_IM1_BANK_ACCOUNT_RECID.NEXTVAL, 'Mikhail Tal', 'DW34G78K34L294', 'Private Bank', '2084');

select * from TH_IM1_BANK_ACCOUNT;
select * from TH_IM1_CREDIT_CARD;
--------------------------------------------------------------------------------

CREATE TABLE "TH_IM2_BANK_ACCOUNT"
(
   TH_BILL_RECID NUMBER,
   TH_BILL_OWNER VARCHAR2(300),
   TH_BACC_ACCOUNT VARCHAR2(100),
   TH_BACC_BANKNAME VARCHAR2(100),
   TH_BACC_SWIFT VARCHAR2(100),
   CONSTRAINT "TH_IM2_BANK_ACCOUNT_PK" PRIMARY KEY("TH_BILL_RECID")
);
CREATE SEQUENCE SEQ_TH_IM2_BILL_RECID MINVALUE 0 START WITH 0 INCREMENT BY 1 NOCACHE NOCYCLE;

INSERT INTO TH_IM2_BANK_ACCOUNT VALUES(SEQ_TH_IM2_BILL_RECID.NEXTVAL, 'Mikhail Botvinnik', 'FW45F32SQ12', 'Private Bank', '2380');
INSERT INTO TH_IM2_BANK_ACCOUNT VALUES(SEQ_TH_IM2_BILL_RECID.NEXTVAL, 'Mikhail Tal', 'DW34G78K34L294', 'Private Bank', '2084');

CREATE TABLE "TH_IM2_CREDIT_CARD"
(
   TH_BILL_RECID NUMBER,
   TH_BILL_OWNER VARCHAR2(300),
   TH_CRC_NUMBER VARCHAR2(25),
   TH_CRC_EXP_MONTH VARCHAR2(10),
   TH_CRC_EXP_YEAR VARCHAR2(5),
   CONSTRAINT "TH_IM2_CREDIT_CARD_PK" PRIMARY KEY("TH_BILL_RECID")
);

INSERT INTO TH_IM2_CREDIT_CARD VALUES(SEQ_TH_IM2_BILL_RECID.NEXTVAL, 'Garry Kasparov', '1234 2345 3456 4567', '23/11', '2018');
INSERT INTO TH_IM2_CREDIT_CARD VALUES(SEQ_TH_IM2_BILL_RECID.NEXTVAL, 'Anatoly Karpov', '2334 4545 8712 3454', '14/07', '2019');
INSERT INTO TH_IM2_CREDIT_CARD VALUES(SEQ_TH_IM2_BILL_RECID.NEXTVAL, 'Mikhail Tal', '4444 7777 3546 6789', '15/08', '2017');
commit;

select * from TH_IM2_BANK_ACCOUNT;
select * from TH_IM2_CREDIT_CARD;
create view THW_IM2_CREDIT_CARD as select * from TH_IM2_CREDIT_CARD;
